# Tugas kuliah SLO (Statistical Learning Optimization) - Kelompok 1

# Kelompok_1

Lyra Vega Ugi - 2101201021;
Ahzanul Kholish - 2101201027;
Annisa Humairani - 2101201028

#### Dataset : Iris.csv
#### Terdiri atas 6 column: Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species
#### Input : SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm
#### Output (Label) : Species --> Iris-setosa, Iris-versicolor, dan Iris-virginica
#### Jumlah data (row) : 150, dengan masing2 tipe 50 sampe
#### Metode: Prediction Artificial Neural Network (ANN)

In [ ]:
# Mempersiapkan package yang akan digunakan
import numpy as np  # library yang digunakan untuk operasi suatu array. perhitungan aljabar linear
import pandas as pd # library yang digunakan untuk pembacaan dataset berupa csv. dataset processing
import os # memperlihatkan  file dataset yang dipakai
os.listdir('Documents/UTS_Kel_1_SLO/Data')

['Iris.csv']

In [ ]:
# Load dataset dari folder
data_iris = pd.read_csv('Documents/Program Python/TUBES_SLO_UTS/dataset_iris/Iris.csv')
print(data_iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [ ]:
# Normalisasi dataset untuk masing-masing column dengan pendekatan skala min - max, sehingga mempunyai fixed range [0,1]
# Xnorm = (X - Xmin) / (Xmax - Xmin)
def min_max_scaling(df):
    # copy the dataframe
    df_norm = df.copy()
    # apply min-max scaling
    for column in df_norm.columns:
        df_norm[column] = (df_norm[column] - df_norm[column].min()) / (df_norm[column].max() - df_norm[column].min())
    return df_norm

In [ ]:
# Normalisai dataset untuk masing-masing column dengan pendekatan skala min - max, sehingga mempunyai fixed range [0,1]
norm_data_iris = min_max_scaling(data_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm','PetalWidthCm']])
print(norm_data_iris)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0         0.222222      0.625000       0.067797      0.041667
1         0.166667      0.416667       0.067797      0.041667
2         0.111111      0.500000       0.050847      0.041667
3         0.083333      0.458333       0.084746      0.041667
4         0.194444      0.666667       0.067797      0.041667
..             ...           ...            ...           ...
145       0.666667      0.416667       0.711864      0.916667
146       0.555556      0.208333       0.677966      0.750000
147       0.611111      0.416667       0.711864      0.791667
148       0.527778      0.583333       0.745763      0.916667
149       0.444444      0.416667       0.694915      0.708333

[150 rows x 4 columns]


In [ ]:
# Konversi Species label setiap kelas menjadi index 0, 1 dan 2
# Iris-setosa = 0
# Iris-versicolor = 1
# Iris-virginica = 2
target_output = data_iris[['Species']].replace(['Iris-setosa','Iris-versicolor','Iris-virginica'],[0,1,2])
print(target_output)

     Species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]


In [ ]:
# Dengan menggunakan pd.concat, maka menggabungkan label ke tabel normalization iris
norm_data_iris = pd.concat([norm_data_iris, target_output], axis=1)
print(norm_data_iris)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0         0.222222      0.625000       0.067797      0.041667        0
1         0.166667      0.416667       0.067797      0.041667        0
2         0.111111      0.500000       0.050847      0.041667        0
3         0.083333      0.458333       0.084746      0.041667        0
4         0.194444      0.666667       0.067797      0.041667        0
..             ...           ...            ...           ...      ...
145       0.666667      0.416667       0.711864      0.916667        2
146       0.555556      0.208333       0.677966      0.750000        2
147       0.611111      0.416667       0.711864      0.791667        2
148       0.527778      0.583333       0.745763      0.916667        2
149       0.444444      0.416667       0.694915      0.708333        2

[150 rows x 5 columns]


In [ ]:
# Define persentase data untuk \"test\", dan buat satu column (\"training\") untuk menentukan apakah data row untuk training atau test
# True = data trainig
# False = data test
persentase_test_training = 90/100.0 #data training yang diambil adalah 90% dari jumlah dataset
norm_data_iris['training'] = np.random.rand(len(norm_data_iris)) < persentase_test_training
#len(norm_data_iris)
print(norm_data_iris)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species  \
0         0.222222      0.625000       0.067797      0.041667        0   
1         0.166667      0.416667       0.067797      0.041667        0   
2         0.111111      0.500000       0.050847      0.041667        0   
3         0.083333      0.458333       0.084746      0.041667        0   
4         0.194444      0.666667       0.067797      0.041667        0   
..             ...           ...            ...           ...      ...   
145       0.666667      0.416667       0.711864      0.916667        2   
146       0.555556      0.208333       0.677966      0.750000        2   
147       0.611111      0.416667       0.711864      0.791667        2   
148       0.527778      0.583333       0.745763      0.916667        2   
149       0.444444      0.416667       0.694915      0.708333        2   

     training  
0        True  
1        True  
2        True  
3       False  
4       False  
..        ...  

In [ ]:
# Buat dataset untuk training
training_data_iris = norm_data_iris[norm_data_iris.training == True] #mengambil data train dengan norm_data_iris = true
training_data_iris = training_data_iris.drop('training',axis=1).sample(frac=1) #menghilangkan kolom 'train' yang menampilkan true dan false
#len(training_data_iris)
print(training_data_iris) #menampilkan training_data_iris sebanyak 92% dari dataset

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
89        0.333333      0.208333       0.508475      0.500000        1
122       0.944444      0.333333       0.966102      0.791667        2
47        0.083333      0.500000       0.067797      0.041667        0
101       0.416667      0.291667       0.694915      0.750000        2
100       0.555556      0.541667       0.847458      1.000000        2
..             ...           ...            ...           ...      ...
23        0.222222      0.541667       0.118644      0.166667        0
51        0.583333      0.500000       0.593220      0.583333        1
40        0.194444      0.625000       0.050847      0.083333        0
108       0.666667      0.208333       0.813559      0.708333        2
16        0.305556      0.791667       0.050847      0.125000        0

[138 rows x 5 columns]


In [ ]:
# Buat dataset untuk test
test_data_iris = norm_data_iris[norm_data_iris.training == False] #mengambil data test dengan norm_data_iris = false
test_data_iris = test_data_iris.drop('training',axis=1).sample(frac=1) #menghilangkan kolom 'train' yang menampilkan true dan false
#len(test_data_iris)
print(test_data_iris) #menampilkan training_data_iris sebanyak 8% dari dataset

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
140       0.666667      0.458333       0.779661      0.958333        2
3         0.083333      0.458333       0.084746      0.041667        0
36        0.333333      0.625000       0.050847      0.041667        0
146       0.555556      0.208333       0.677966      0.750000        2
133       0.555556      0.333333       0.694915      0.583333        2
62        0.472222      0.083333       0.508475      0.375000        1
4         0.194444      0.666667       0.067797      0.041667        0
88        0.361111      0.416667       0.525424      0.500000        1
99        0.388889      0.333333       0.525424      0.500000        1
110       0.611111      0.500000       0.694915      0.791667        2
14        0.416667      0.833333       0.033898      0.041667        0
144       0.666667      0.541667       0.796610      1.000000        2


In [ ]:
# Mendefinisikan training input\n",
training_inputs = training_data_iris.values[:,:4]
#len(training_inputs)
print(training_inputs)

[[0.33333333 0.20833333 0.50847458 0.5       ]
 [0.94444444 0.33333333 0.96610169 0.79166667]
 [0.08333333 0.5        0.06779661 0.04166667]
 [0.41666667 0.29166667 0.69491525 0.75      ]
 [0.55555556 0.54166667 0.84745763 1.        ]
 [0.22222222 0.75       0.10169492 0.04166667]
 [0.33333333 0.16666667 0.45762712 0.375     ]
 [0.41666667 0.29166667 0.69491525 0.75      ]
 [0.52777778 0.33333333 0.6440678  0.70833333]
 [0.33333333 0.125      0.50847458 0.5       ]
 [0.66666667 0.54166667 0.79661017 0.83333333]
 [0.25       0.875      0.08474576 0.        ]
 [0.66666667 0.45833333 0.57627119 0.54166667]
 [0.08333333 0.66666667 0.         0.04166667]
 [0.69444444 0.5        0.83050847 0.91666667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.41666667 0.25       0.50847458 0.45833333]
 [0.22222222 0.625      0.06779661 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.69444444 0.41666667 0.76271186 0.83333333]
 [0.27777778 0.70833333 0.08474576 0.04166667]
 [0.52777778 

In [ ]:
# Mendefinikan target outputs, dimana:
# [1,0,0] = Iris-setosa
# [0,1,0] = Iris-versicolor
# [0,0,1] = Iris-virginica
target_outputs = [[1,0,0],[0,1,0],[0,0,1]]
target_outputs = np.array([target_outputs[int(x)] for x in training_data_iris.values[:,4:5]]) 
#len(target_outputs)
target_outputs

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1,

# Membuat neural network forward propagation & back propagation

Membuat neural network forward propagation
3 layer yang dibuat: Input, hidden dan Output.

Inputs = length dan width dari setiap species (fiturnya)
Output = ada 3 masing-masingnya menandai bahwa itu speciesnnya. 
Contohnya adalah nilai 1, 0, 0 untuk output Iris-setosa atau 0, seperti yang sudah dijelaskan sebelumnya.

synaptic_weights_1 adalah matriks dari weight yang menghubungkan input dan hidden layer. 
Setiap node di input layer menghubungkan masing-masing node di hidden layer.
Input dikalikan weight lalu sigmoid dari sum input*weight akan menghasilkan output. 
Pada forward propagation akan mencari erornya, yaitu selisih dari prediksi output dengan actual output

Membuat neural network backward propagation
Error yang kita dapat pada forward propagation akan digunakan untuk adjustment.
Adjustmen weightnya dengan backward propagation dengan rumus eror*input*turunan pertama output. Lalu akan mendapatkan adjustment_.

Weight sebelumnya ditambahkan adjustment weight, dengan mengupdate setiap weight dan hidden layer dengan learning rate tertentu.
Pada saat adjust weight nilai weight akan berubah-ubah nilainya lalu akan dimasukan kedalam rumus sigmoid.

Kedua proses diatas akan dilakukan berulang-ulang sampai didapatkan nilai weight dan hidden layer yang dapat memberikan nilai error sekecil mungkin pada output layer (pada saat forward propagation).
    
Proses akan dilakukan dari forward propagation dan backwarard propagation seterusnya dilakukan berulang kali sampai akurasi sesuai yang kita inginkan.

In [ ]:
# Mendefinisikan jumlah input, hidden layer dan weighting (synaptic) antara input dan hidden layer
jumlah_input = len(training_inputs[0])

#jumlah_input
jumlah_neuron_hidden_layer = 5

# generate weighting (synaptic) antara input dan hidden layer
np.random.seed(1) #seed untuk menghasilkan data yang sama pada nilai randomnya
synaptic_weights_1 = 2 * np.random.random((jumlah_input,jumlah_neuron_hidden_layer))-1 #perhitungan weight_1= menghasilkan jumlah weights dengan cara random dari jumlah input *2 -1

print(synaptic_weights_1)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
 [-0.81532281 -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481]
 [ 0.34093502 -0.1653904   0.11737966 -0.71922612 -0.60379702]]


In [ ]:
# generate weighting (synaptic) antara hidden-layer dan output

jumlah_output = len(target_outputs[0]) 

#jumlah_output
synaptic_weights_2 = 2 * np.random.random((jumlah_neuron_hidden_layer, jumlah_output))-1 #perhitungan weight_2= menghasilkan jumlah weights dengan cara random dari jumlah input *2 -1
synaptic_weights_2

array([[ 0.60148914,  0.93652315, -0.37315164],
       [ 0.38464523,  0.7527783 ,  0.78921333],
       [-0.82991158, -0.92189043, -0.66033916],
       [ 0.75628501, -0.80330633, -0.15778475],
       [ 0.91577906,  0.06633057,  0.38375423]])

In [ ]:
# define fungsi sigmoid
def sigmoid(x):
    return 1/(1+np.exp(-x)) #dengan menggunakan rumus sigmoid normalization function 1/1+e^-x

In [ ]:
# define fungsi turunan signoid\n",
def sigmoid_derivative(x):
    return x * (1 - x) #untuk mengecek gradient dari fungsinya

Dengan menggunakan persamaan-persamaan dibawah ini, kemudian realisasikan kedalam codingan

# Forward Propagation
    sigmoid 
    sigmoid sum (xi.wi) = x1.w1 + x2.w2 + x3.w3 + ...+ xn.wn
    
    sigmoid normalizing function
    sigmoid (x) = 1/1+eksponen^(-x) --> sigmoid(x) = 1/+ eksponen ^(-sum xi.wi)
    
    error
    error = output - actual output
    
    
# Back Propagation 
    sigmoid_derivative
    sigmoid_derivative(x) = x.(1-x)
    
    adjust weights
    adjust weights= error . input . sigmoid_derivative(output)
    
    synaptic weights
    synaptic weights= [input layer]T dot product [adjust weights]
    

In [ ]:
# Iteration process
learning_rate = 0.01
for i in range(50000):
    # Analisa forward propagation untuk perhitungan output dan kalkulasi error
    outputs_1 = sigmoid(np.dot(training_inputs,synaptic_weights_1)) # aktivasi nilai pada hidden layer
    outputs_2 = sigmoid(np.dot(outputs_1,synaptic_weights_2)) # aktivasi nilai pada output layer
    error = (target_outputs - outputs_2) #selisih nilai outputs dengan actual outputs
    error_mean = abs(error).mean()

    # Analisa back propagation untuk mendapatkan adjustment dan update weighting
    adjustment_2 = error * sigmoid_derivative(outputs_2) #adjustment output layer
    adjustment_1 = adjustment_2.dot(synaptic_weights_2.T) * sigmoid_derivative(outputs_1) #adjustment hidden layer

    synaptic_weights_2 += outputs_1.T.dot(adjustment_2) * learning_rate #update weight output layer
    synaptic_weights_1 += training_inputs.T.dot(adjustment_1) * learning_rate #update weight hidden layer

print('synaptic weight antara input dan hidden layer setelah training: ')
print(synaptic_weights_1)

print('synaptic weight antara hidden layer dan output setelah training: ')
print(synaptic_weights_2)

print('output setelah training: ')
print(outputs_2)

#print("Error: ")
#print(error)

print("Error Mean: ")
print(error_mean)

synaptic weight antara input dan hidden layer setelah training: 
[[  4.34590065   3.41528947   0.01757905  -2.98000571  -3.08805909]
 [ -3.55216013 -10.07157326  -1.00946938   4.59778303  11.21680823]
 [ -4.37181849   8.23119468   1.06153072   0.96118893  -8.68718359]
 [  0.34459892   5.43612365   1.58169063  -3.29328153  -5.51934784]]
synaptic weight antara hidden layer dan output setelah training: 
[[  1.58021422  19.29249256 -26.23446222]
 [ -5.02669566  14.32300031  -2.02795645]
 [ -2.21091257 -26.6071787   14.90319886]
 [  3.6972803   17.51823489 -25.8763102 ]
 [  6.64726476 -20.26889013  -8.27981647]]
output setelah training: 
[[4.16542730e-03 9.01070119e-01 9.55678238e-02]
 [1.71547126e-03 4.49472029e-02 9.45706069e-01]
 [9.99884997e-01 4.52326656e-06 2.74667873e-13]
 [2.20030242e-03 4.88268587e-02 9.65904309e-01]
 [1.87880479e-03 6.13641235e-03 9.95548472e-01]
 [9.99922925e-01 1.31961584e-05 9.07907529e-14]
 [5.79375596e-03 9.92609878e-01 5.25559828e-03]
 [2.20030242e-03 4.8826

In [ ]:
# Prediction menggunakan test dataset

test_inputs = test_data_iris.values[:,:4]
len(test_inputs)
target_outputs = [[1,0,0],[0,1,0],[0,0,1]]
target_outputs = np.array([target_outputs[int(x)] for x in test_data_iris.values[:,4:5]])
# print(target_outputs)

outputs_1 = sigmoid(np.dot(test_inputs,synaptic_weights_1)) # output pada hidden layer
outputs_2 = sigmoid(np.dot(outputs_1,synaptic_weights_2)) # estimasi pada output layer 


print(np.round(outputs_2,3)) # Estimasi output

# print(np.around(outputs_2))

[[0.002 0.011 0.992]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.002 0.14  0.852]
 [0.003 0.499 0.54 ]
 [0.004 0.994 0.003]
 [1.    0.    0.   ]
 [0.01  0.985 0.004]
 [0.006 0.963 0.025]
 [0.003 0.166 0.859]
 [1.    0.    0.   ]
 [0.002 0.008 0.995]]


In [ ]:
# Hasil Prediksi

prediksi = np.around(outputs_2) #membulatkan hasil pada outputs

# Discrepancy hasil estimasi dengan yang seharusnya 
discrepancy = np.argmax(prediksi, axis=1) == np.argmax(target_outputs, axis=1) # bandingkan hasil prediksi dengan label target
# print(discrepancy)

# Menghitung persentase hasil yang benar terhadap semua hasil test
presentase_benar = np.sum(discrepancy)/len(discrepancy)
# print(presentase_benar)

hasil_test = test_data_iris[['Species']].replace([0,1,2],['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
hasil_test['Prediction'] = np.argmax(outputs_2, axis=1)
hasil_test['Prediction'] = hasil_test['Prediction'].replace([0,1,2],['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])

print(hasil_test)
print('')
print('Correct: ', sum(discrepancy), ' / ', len(hasil_test), (presentase_benar*100), '%')

             Species       Prediction
140   Iris-virginica   Iris-virginica
3        Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
146   Iris-virginica   Iris-virginica
133   Iris-virginica   Iris-virginica
62   Iris-versicolor  Iris-versicolor
4        Iris-setosa      Iris-setosa
88   Iris-versicolor  Iris-versicolor
99   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
14       Iris-setosa      Iris-setosa
144   Iris-virginica   Iris-virginica

Correct:  12  /  12 100.0 %


# Kesimpulan

Di Tugas SLO ini, kami menyajikan metode Artificial Neural Network (ANN) untuk memprediksi bunga Iris dengan 3 *species* atau kelas, yaitu Iris-virginica, Iris-setosa, dan Iris-versicolor. Setelah dinormalisasi, *dataset* dibagi menjadi dua, yaitu data *training* dan *testing*, dengan jumlah data *training* adalah 90/100 (90%) dari keseluruhan *dataset* dan data *testing* adalah sisanya. ANN yang terdiri dari 5 *hidden layer* diuji menjadi suatu metode yang sangat menguntungkan dalam melakukan prediksi dengan waktu komputasi yang cepat untuk 150 data pada CSV file. Hasil tertinggi yang dicapai menggunakan ANN adalah 0.04235 *error mean* dan 100% akurasi.